baseURL = "https://shronkers.github.io/"
title = "grigoriyagas.tech"
theme = "risotto"

pluralizeListTitles = false

[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true

[params.about]
	title = "grigoriyagas.tech"
	description = "Grigoriy Agasyants's personal website"

[menu]
	[[menu.main]]
		identifier = "portfolio"
		name = "portfolio"
		url = "/portfolio"
		weight = 10
	[[menu.main]]
		identifier = "blog"
		name = "blog"
		url = "/blog"